### ISSUE TITLE
Running in Google Cloud

### ISSUE THREAD

**Issue by Strydom** [MaximilianMeister/kuberneteth#9]
I've been trying to get this running in Google cloud and just wanted to check a few things that don't seem right...

**First**: there are 3 boot-node-setup pods and 2 monitor replicas, is that normal?
```
$ kubectl get pods
NAME                                    READY     STATUS    RESTARTS   AGE
geth-boot-node-pod                      1/1       Running   0          42m
geth-boot-node-setup-pod-h5wq9          1/1       Running   0          42m
geth-boot-node-setup-pod-jjnqc          1/1       Running   0          42m
geth-boot-node-setup-pod-xh7cz          1/1       Running   0          42m
geth-miner-deployment-d97db8bc6-vb9ds   1/1       Running   0          42m
monitor-deployment-ffc657f7d-zjhst      2/2       Running   0          42m
```

**Second**: I've exposed 1 mining node and the Monitor with a LoadBalancer so that I can use it as a Provider for a local testing app and view the monitor. As mentioned in #8 I'm not able to see any allocated funds only funds mined into an Etherbase, I'm not sure if this is related? More importantly I can't see the second miner in the Monitor. miner0 does have miner1 as a peer though.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: miner0-svc
  labels:
    app: kuberneteth
    tier: backend
    name: miner0-svc
spec:
  selector:
    app: kuberneteth
    tier: backend
  type: NodePort
  ports:
    - name: miner0-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30001
    - name: miner0-wsrpc
      protocol: TCP
      port: 8547
      targetPort: 8547
    - name: miner0-ipc-listen
      protocol: UDP
      port: 30301
      targetPort: 30301
    - name: miner0-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 31001

---
apiVersion: v1
kind: Service
metadata:
  name: miner0-web-svc
  labels:
    app: kuberneteth
    tier: backend
    name: miner0-web-svc
spec:
  selector:
    app: kuberneteth
    tier: backend
  type: LoadBalancer
  ports:
    - name: miner0-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: miner0-wsrpc
      protocol: TCP
      port: 8547
      targetPort: 8547

---
apiVersion: v1
kind: Service
metadata:
  name: miner1-svc
  labels:
    app: kuberneteth
    tier: backend
    name: miner1-svc
spec:
  selector:
    app: kuberneteth
    tier: backend
  type: NodePort
  ports:
    - name: miner1-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
      nodePort: 30002
    - name: miner1-wsrpc
      protocol: TCP
      port: 8547
      targetPort: 8547
    - name: miner1-ipc-listen
      protocol: UDP
      port: 30301
      targetPort: 30301
    - name: miner1-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 31002
```

Monitor-config:
```json
[
      {
        "name"              : "miner0",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "miner0-rpchost",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "miner0",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "connectme",
          "VERBOSITY"       : 0
        }
      },
      {
        "name"              : "miner1",
        "cwd"               : ".",
        "script"            : "app.js",
        "log_date_format"   : "YYYY-MM-DD HH:mm Z",
        "merge_logs"        : false,
        "watch"             : false,
        "exec_interpreter"  : "node",
        "exec_mode"         : "fork_mode",
        "env":
        {
          "NODE_ENV"        : "production",
          "RPC_HOST"        : "miner1-rpchost",
          "RPC_PORT"        : "8545",
          "LISTENING_PORT"  : "30303",
          "INSTANCE_NAME"   : "miner1",
          "CONTACT_DETAILS" : "",
          "WS_SERVER"       : "localhost:3001",
          "WS_SECRET"       : "connectme",
          "VERBOSITY"       : 0
        }
      }
]
```

Here are my services:
```
$ kubectl get services
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                         AGE
geth-bootnode-svc   ClusterIP      10.23.242.147   <none>          30303/UDP                                                       43m
kubernetes          ClusterIP      10.23.240.1     <none>          443/TCP                                                         11h
miner0-svc          NodePort       10.23.251.110   <none>          8545:30001/TCP,8547:30947/TCP,30301:31290/UDP,30303:31001/TCP   43m
miner0-web-svc      LoadBalancer   10.23.249.206   xx.xxx.xxx.xx   8545:30369/TCP,8547:30542/TCP                                   43m
miner1-svc          NodePort       10.23.244.106   <none>          8545:30002/TCP,8547:31385/TCP,30301:32750/UDP,30303:31002/TCP   41m
monitor-svc         LoadBalancer   10.23.254.254   xx.xxx.xx.xxx   80:30623/TCP                                                    43m
```

Hope you can shine some light on this,
Many thanks.
